### ISSUE TITLE
 can't handle scopes packages

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/whatif#2] opened 2016-07-28 08:45 UTC
I have a package directory:
module1

but the package.json contains a scoped package name:
"name": "@/module1"

whatif does not read the 'name' from the package, and only searches for 'module1' - since the other modules contain a reference to the scoped name, it won't find the dependency:
"@/module1": "0.2.6"

**Comment by goloroden** [comment] 2016-11-15 08:22
Can you please add a few specific steps on how to reproduce the problem?

**Comment by goloroden** [comment] 2016-11-15 08:34
Basically, the problem is that the way whatif is implemented today you have to provide the name of the package, not its directory, as the documentation states:

> To simplify this task you can run whatif within the directory that contains all of your repositories. Provide the name of an updated package as a parameter:
>
> $ whatif <package>

If you provide the full name, including the `@org/` prefix, everything works as expected.

I understand that having a scoped module is an edge case here, because the name of the module does not match the name of the directory that contains the module. The only workaround would be to check whether there is a directory with the given name, and if so, check whether it contains a `package.json`, and if so, read the name from there, and otherwise use the given name as-is.

**Comment by goloroden** [comment] 2016-11-15 08:45
Fixed in release 0.1.2.

**Closed** 2016-11-15 08:44 UTC
